### ISSUE TITLE
 Is this mod legal?

### ISSUE THREAD

**Issue by Fran1P37** [qimiko/click-on-steps#8]
Hola. Vi este mod en Geode, y me intereso que es lo que hacia, pero me entro una gran duda is legal?. En su descripcion dice que ''teoricamente deberia ser legal'', pero realmente lo es? si alguien pudiera resolverme esa duda le agradeceria.
![descarga (1)](https://github.com/qimiko/click-on-steps/assets/159739249/45e192e7-7e85-4a27-9404-74bc6e66a940)

**Comment by qimiko** [comment]
nobody has been arrested for using this mod, but you never know...

as for the leaderboard safe claim, the "theoretically" part is because i have not actually seen any indication that it is (or is not) allowed. the rules officially state that any gameplay modifications are not allowed, but this mod is identical to playing the game at 240fps.
